added a busy loop into all the code and some comments. We're done wit…
uofu-emb/Lab05_Skylar_Shem_F24 pull request #1
Opened 2024-10-29 16:35 UTC by shem-snow

We did the thing. Our code has busy loops in it.

2024-10-30 19:15 UTC, SamBosch77 commented
Keep in mind that item 11 under measuring jitter asks to calculate the expected drift over a one-hour period. I didn't see any calculations for that in the README, so you may want to add that

2024-11-03 00:22 UTC, VarunBhavya requested changes
I’ve noticed that in all files, there is an incrementing loop that continues until a count of 36 is reached. However, there are no comments explaining the reasoning behind this specific choice of 36. Could you provide some context on why this value was selected? Understanding this will help me before approving the pull request.

2024-11-03 00:22 UTC, VarunBhavya commented on src/gpio_interrupt.c
It appears that the `busy_loop` function is defined, yet I don't see it being utilized within the `irq_callback` function. Instead, the code implements a sleep for 36 ms. Could you clarify if this is an oversight, or is there a specific reason for not using the `busy_loop` function in this context?

2024-11-27 21:38 UTC, shem-snow commented on src/gpio_interrupt.c
We didn't realize there was already a busy_loop function and made our own. The amount of time is not relavant.

2024-12-05 17:59 UTC, merged